mysite/booker/urls.py
from django.conf.urls import url

from . import views

from django.conf.urls import include, url 
from django.contrib import admin 
from django.views.generic import TemplateView


urlpatterns = [ 
	#url(r'^$', TemplateView.as_view(template_name="home.html"), name="home"), 
	#url( r'^users/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name="user-logout" ), 
]

mysite/mysite/urls.py
"""from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
	url(r'^booker/', include('booker.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include('social.apps.django_app.urls', namespace='social')),
]"""

import django


from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from booker import views
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import *


urlpatterns = [ 
	url(r'^admin/', include(admin.site.urls)),
	# Python Social Auth URLs
	url('', include('social.apps.django_app.urls', namespace='social')),
	url(r'^accounts/', include('registration.urls')),
	# Home URL
	url(r'^$', TemplateView.as_view(template_name="home.html"), name="home"),

    #FORMULARIO
	

    #CKEDITOR
    url(r'^editor/', views.Libros2CreateView.as_view(success_url='/editor'), name="editor" ),
    #url(r'^editor2/'

    #TODOS LOS LIBROS
	url(r'^hecho/', views.LibrosListView.as_view(), name="hecho"),

    #BORRAR CAPITULOS
    url(r'^borrar/(?P<pk>\d+)/$', views.CapitulosDeleteView.as_view(), name='delete'),
    #BORRAR LIBROS
    url(r'^borrarlibros/(?P<pk>\d+)/$', views.LibrosDeleteView.as_view(), name='delete2'),
    #EDITAR LIBROS
    url(r'^editarcapitulos/(?P<pk>\d+)/$', views.EditorCapitulos.as_view(), name='update'),
    #Separador crear o subir libro
    url(r'^sube_o_crea/', views.SubeCreaLibro.as_view(), name="sube_o_crea"),
    url(r'^crea/', views.LibrosDesdeCero.as_view(success_url='/editor'),name="crea"),
    url(r'^sube/', views.LibrosCreateView.as_view(success_url='/hecho'), name="sube" ),

    #GENEROS
    url(r'^accion/', views.LibrosAccionListView.as_view(), name="accion"),
    url(r'^aventura/', views.LibrosAventuraListView.as_view(), name="aventura"),
    url(r'^cienciaficcion/', views.LibrosCienciaFiccionListView.as_view(), name="cienciaficcion"),
    url(r'^humor/', views.LibrosHumorListView.as_view(), name="humor"),
    url(r'^misterio/', views.LibrosMisterioListView.as_view(), name="misterio"),
    url(r'^romance/', views.LibrosRomanceListView.as_view(), name="romance"),
    url(r'^poesia/', views.LibrosPoesiaListView.as_view(), name="poesia"),
    url(r'^terror/', views.LibrosTerrorListView.as_view(), name="terror"),
    url(r'^drama/', views.LibrosDramaListView.as_view(), name="drama"),
    url(r'^otros/', views.LibrosOtrosListView.as_view(), name="otros"),

    #FAQ
    url(r'^faq/', views.Faq.as_view(), name="faq"),

	# Logout URL
	#url( r'^logout/$', auth_views.LogoutView.as_view() , {'next_page': '/'}, name="user-logout" ),

    #Visualizador capitulos
    url(r'^visualizador/(?P<visualiza>[0-9]{0,10})/', views.visualizadorlibros , name="visualizador"),
    url(r'^visualizador2/(?P<visualiza2>[0-9]{0,10})/', views.visualizadorcapitulos , name="visualizador2"),


	#url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
    #   'document_root': settings.STATIC_ROOT
    #}),
    url(r'^media/(?P<path>.*)$', django.views.static.serve, {
        'document_root': settings.MEDIA_ROOT
    }),
    url(r'^djrichtextfield/', include('djrichtextfield.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'^comments/', include('django_comments.urls')),

]

#urlpatterns += staticfiles_urlpatterns()
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/booker/models.py
from __future__ import unicode_literals

from django.db import models
from datetime import datetime
from ckeditor.fields import RichTextField
from django.contrib.contenttypes.fields import GenericRelation
from star_ratings.models import Rating
from django.contrib.auth.models import User

# Create your models here.

class Genero(models.Model):
	"""docstring for Missatges"""
	nombre=models.CharField(max_length=20,default='')
	"""incidencia=models.CharField(max_length=120)"""
	"""usuaris=models.ManyToManyField(Usuaris)"""
	def __str__(self):
		return self.nombre


class Libros(models.Model):
	"""docstring for Hashtags"""
	"""identificador=models.IntegerField(default=0)"""
	"""departament=models.ForeignKey(Departaments)"""
	autores=models.ManyToManyField(User)
	nombre=models.CharField(max_length=50, default='')
	genero=models.ManyToManyField(Genero)
	portada=models.ImageField(upload_to='booker/images')
	contenido=models.FileField(upload_to='booker/libros',blank=True, null=True)
	sinopsis=models.TextField(max_length=600,default='')
	ratings = GenericRelation(Rating, related_query_name='foos')
	
	
	def __str__(self):
		return self.nombre

class Capitulos(models.Model):
	nombre=models.CharField(max_length=50, default='')
	libro=models.ForeignKey(Libros,default='')
	content = RichTextField(verbose_name='BookContent',null=True,blank=True)

	def __str__(self):
		return self.nombre

		

mysite/booker/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView
from django.views.generic.edit import UpdateView
from django.http import HttpResponse
from django import forms
from booker.models import *
# Create your views here.

from django.contrib.auth import logout

def logout_view(request):
    logout(request)
    return render( request, 'visualizadorlibros.html')


class EditorForm(forms.ModelForm):
    class Meta:
       model = Capitulos
       fields = ['nombre','libro','content']

    def __init__(self, *args, **kwargs):
       user = kwargs.pop('user')
       super(EditorForm, self).__init__(*args, **kwargs)
       self.fields['libro'].queryset = Libros.objects.filter(autores=user)

class Faq(CreateView):
	model = Libros
	# indiquem la plantilla personalitzada i els camps que han d'apareixer al formulari
	# veureu que la plantilla es molt senzilla ja que fa tot el formulari amb {{form.as_p}}
	template_name = "faq.html"
	fields = ['nombre','autores','genero','portada','contenido','sinopsis']

class SubeCreaLibro(CreateView):
	model = Libros
	template_name = "subecrealibro.html"
	fields = ['nombre','autores','genero','portada','contenido','sinopsis']

class LibrosCreateView(CreateView):
	model = Libros
	# indiquem la plantilla personalitzada i els camps que han d'apareixer al formulari
	# veureu que la plantilla es molt senzilla ja que fa tot el formulari amb {{form.as_p}}
	template_name = "libros.html"
	fields = ['nombre','autores','genero','portada','contenido','sinopsis']

class LibrosDesdeCero(CreateView):
	model = Libros
	# indiquem la plantilla personalitzada i els camps que han d'apareixer al formulari
	# veureu que la plantilla es molt senzilla ja que fa tot el formulari amb {{form.as_p}}
	template_name = "librosdesdecero.html"
	fields = ['nombre','autores','genero','portada','sinopsis']

class Libros2CreateView(CreateView):
	# indiquem la plantilla personalitzada i els camps que han d'apareixer al formulari
	# veureu que la plantilla es molt senzilla ja que fa tot el formulari amb {{form.as_p}}
	template_name = "editor.html"
	form_class = EditorForm

	def get_form_kwargs(self):
		kwargs = super(Libros2CreateView, self).get_form_kwargs()
		kwargs['user'] = self.request.user
		return kwargs

class CapitulosDeleteView(DeleteView):
	model = Capitulos
	success_url = '/hecho'
	template_name = 'capitulos_confirm_delete.html'

	def get_queryset(self):
		folders = Capitulos.objects.filter(libro__autores=self.request.user)
		return folders

class LibrosDeleteView(DeleteView):
	model = Libros
	success_url = '/hecho'
	template_name = 'capitulos_confirm_delete.html'

	def get_queryset(self):
		folders = Libros.objects.filter(autores=self.request.user)
		return folders

class EditorCapitulos(UpdateView):
    model = Capitulos
    success_url = '/hecho'
    fields = ['nombre','content']
    template_name = 'editorcapitulos.html'

#VIEW PERSONALIZADA
#VIEW Para pasar capitulos
def visualizadorlibros(request,visualiza):
	identificador = visualiza
	
	capitulos = Capitulos.objects.filter(libro=identificador).order_by('id')

	#for capitulo in capitulos:
	

	
	return render( request, 'visualizadorlibros.html' , {"caps":capitulos} )



def visualizadorcapitulos(request,visualiza2):
	identificador2 = visualiza2

	capitulos = Capitulos.objects.filter(id=identificador2)

	borrable = False
	for cap in capitulos:
		if request.user in cap.libro.autores.all() :
			borrable = True

	return render( request, 'visualizadorcapitulos.html' , {"caps":capitulos,"borrable":borrable} )

class LibrosListView(ListView):
	model = Libros
	template_name = "libroshecho.html"
	# si no posem template_name agafara per defecte karaoke/item_list.html
	def get_queryset(self):

		# nomes posem els items que estiguin per cantar
		return Libros.objects.all()
		#.filter(fet=False)

class LibrosAccionListView(ListView):
	model = Libros
	template_name = "libroshechoaccion.html"

	def get_queryset(self):
		# nomes posem els items que estiguin per cantar
		return Libros.objects.all()
		#.filter(fet=False)

class LibrosAventuraListView(ListView):
	model = Libros
	template_name = "libroshechoaventura.html"
	
	def get_queryset(self):
		# nomes posem els items que estiguin per cantar
		return Libros.objects.all()
		#.filter(fet=False)

class LibrosCienciaFiccionListView(ListView):
	model = Libros
	template_name = "libroshechocienciaficcion.html"
	
	def get_queryset(self):
		# nomes posem els items que estiguin per cantar
		return Libros.objects.all()
		#.filter(fet=False)

class LibrosHumorListView(ListView):
	model = Libros
	template_name = "libroshechohumor.html"
	
	def get_queryset(self):
		# nomes posem els items que estiguin per cantar
		return Libros.objects.all()
		#.filter(fet=False)

class LibrosMisterioListView(ListView):
	model = Libros
	template_name = "libroshechomisterio.html"
	
	def get_queryset(self):
		# nomes posem els items que estiguin per cantar
		return Libros.objects.all()
		#.filter(fet=False)

class LibrosRomanceListView(ListView):
	model = Libros
	template_name = "libroshechoromance.html"
	
	def get_queryset(self):
		# nomes posem els items que estiguin per cantar
		return Libros.objects.all()
		#.filter(fet=False)

class LibrosPoesiaListView(ListView):
	model = Libros
	template_name = "libroshechopoesia.html"
	
	def get_queryset(self):
		# nomes posem els items que estiguin per cantar
		return Libros.objects.all()
		#.filter(fet=False)

class LibrosTerrorListView(ListView):
	model = Libros
	template_name = "libroshechoterror.html"
	
	def get_queryset(self):
		# nomes posem els items que estiguin per cantar
		return Libros.objects.all()
		#.filter(fet=False)

class LibrosDramaListView(ListView):
	model = Libros
	template_name = "libroshechodrama.html"
	
	def get_queryset(self):
		# nomes posem els items que estiguin per cantar
		return Libros.objects.all()
		#.filter(fet=False)

class LibrosOtrosListView(ListView):
	model = Libros
	template_name = "libroshechootros.html"
	
	def get_queryset(self):
		# nomes posem els items que estiguin per cantar
		return Libros.objects.all()
		#.filter(fet=False)

mysite/booker/templates/capitulos_confirm_delete.html
{% extends "home.html" %}

{% block content %}

<form method="post">{% csrf_token %}
    ¿Estás seguro que deseas borrarlo?<br/>
    <input type="submit" value="Si" />
</form>

{% endblock %}

mysite/booker/templates/faq.html
{% extends "home.html" %}
{% load i18n %}

{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
{% block content %}
<div class="container register">
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12" >
			<h2>FAQ</h2>

			<h5><strong>¿En qué consiste Booker?</strong></h5>
				<p>Booker se aprovecha del uso de publicaciones de dominio público y de todo autor que prefiera publicar su obra sin ánimo de lucro con el fin que prefiera: divulgación, hobby, etc.</p><br/>

			<h5><strong>¿Cómo puedo publicar una obra?</strong></h5>
				<p>El usuario tiene dos vías para publicar su obra: mediante el editor Booker o subiendo su propia obra mediante un formulario. Para lograr ambas cosas, el usuario debe haber iniciado sesión con su usuario y contraseña, rellenando y siguiendo los pasos que se encontrará en la página seleccionada.</p><br/>
			
			<h5><strong>¿Qué licencias me puede facilitar Booker al realizar mi obra?</strong></h5>
			<p>Las licencias que puede proporcionar Booker para proteger al usuario o autor son las propias de Creative Commons:</p>
			<div class="table-responsive">
			<table class="table table-bordered">
				<tr>
					<th>Atribución (BY)</th>
					<th>No Comercial (NC)</th>
					<th>No Derivadas (ND)</th>
					<th>Compartir Igual (SA)</th>
				</tr>
				<tr>
					<td>El beneficiario de la licencia tiene el derecho de copiar, distribuir, exhibir y representar la obra y hacer obras derivadas siempre y cuando reconozca y cite la obra de la forma especificada por el autor o el licenciante.</td>
					<td>El beneficiario de la licencia tiene el derecho de copiar, distribuir, exhibir y representar la obra y hacer obras derivadas para fines no comerciales.</td>
					<td>El beneficiario de la licencia solamente tiene el derecho de copiar, distribuir, exhibir y representar copias literales de la obra y no tiene el derecho de producir obras derivadas.</td>
					<td>El beneficiario de la licencia tiene el derecho de distribuir obras derivadas bajo una licencia idéntica a la licencia que regula la obra original.</td>
				</tr>
			</table>
			</div>
			<sub>Más info:http://es.creativecommons.org/blog/licencias/</sub>

			<p>Para hacer efectiva la licencia, es preferible que el usuario entre en <a href="https://creativecommons.org/choose/">creativecommons.org</a> y seleccione la licencia que más desee</p>

			<p>Este es un ejemplo:</p>
			<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.

			<br/><br/>	
			<h5><strong>¿Qué puede hacer Booker cuando se denuncia una obra?</strong></h5>
			<p>Booker se reserva el derecho a eliminar cualquier publicación que no se ajuste a las normativas, sea denunciado por contenido que incite al odio, a la discriminación, atente contra personas vulnerables o viole el derecho del copyright o derecho de autor por el simple hecho de su creación.</p>

			<h2>Normativa de publicación de una obra</h2>
				<ul>
					<li>Las obras publicadas deben ser exclusivamente para obra educativa, divulgativa y obras de dominio público. Cualquier obra que se detecte que se pueda encontrar bajo estas condiciones, se procederá a eliminarla.</li>
					<li>El usuario acepta las condiciones de estas normativas al hacer pública su obra.</li>
					<li>En cualquier momento, siempre y cuando se haya denunciado su obra por parte de algún usuario, se podrá borrar una obra publicada.</li>
					
				</ul>
		</div>
	</div>
</div>
</div>

{% endblock %}

mysite/booker/templates/libroshechoaccion.html
{% extends "home.html" %}


{% block content %}
<div class="container register">

{% load static %}

<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

<h2>Accion</h2>
{% for libros in libros_list %}
	{% for generos in libros.genero.all %}
	{% if generos.nombre == "Accion" %}
	
		<div class="col-md-4 well">
	        <div class="panel panel-primary">
	            <div class="panel-heading">
	                <h3 class="panel-title">{{ libros.nombre }}
	                {% if request.user in libros.autores.all %}
	                <a href="/borrarlibros/{{libros.id}}">&nbsp;&nbsp;
	                <span class="glyphicon glyphicon-trash"></span>
	                </a>
	                {% endif %}
	                </h3>
	            </div>
	                <div class="panel-body">
						
						<br/>
						<p style="text-align: center;">
	                    <a href="/visualizador/{{libros.id}}"><img src="{{libros.portada.url}}" height="324" width="250" ></a>
	                    </p>
	                    <br/>
	                    {{libros.sinopsis}}
	                    
	                    

	                </div>

	                <div class="panel-footer">

	                	{% load ratings %}

						{% ratings libros %}

	                	{% if libros.contenido %}
	                	<a href="{{ libros.contenido.url }}">Descarga</a>
						{% endif %}

	                </div>
	        </div>
	    </div>


	
	{% endif %}
	{% endfor %}
{% endfor %}

</div>
{% endblock %}

mysite/booker/templates/libroshechocienciaficcion.html
{% extends "home.html" %}


{% block content %}
<div class="container register">

{% load static %}

<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

<h2>Ciencia Ficcion</h2>
{% for libros in libros_list %}
	{% for generos in libros.genero.all %}
	{% if generos.nombre == "Ciencia Ficcion" %}
	
		<div class="col-md-4 well">
	        <div class="panel panel-primary">
	            <div class="panel-heading">
	                <h3 class="panel-title">{{ libros.nombre }}
	                {% if request.user in libros.autores.all %}
	                <a href="/borrarlibros/{{libros.id}}">&nbsp;&nbsp;
	                <span class="glyphicon glyphicon-trash"></span>
	                </a>
	                {% endif %}
	                </h3>
	            </div>
	                <div class="panel-body">
						
						<br/>
						<p style="text-align: center;">
	                    <a href="/visualizador/{{libros.id}}"><img src="{{libros.portada.url}}" height="324" width="250" ></a>
	                    </p>
	                    <br/>
	                    {{libros.sinopsis}}
	                    
	                    

	                </div>

	                <div class="panel-footer">

	                	{% load ratings %}

						{% ratings libros %}

	                	{% if libros.contenido %}
	                	<a href="{{ libros.contenido.url }}">Descarga</a>
						{% endif %}

	                </div>
	        </div>
	    </div>


	
	{% endif %}
	{% endfor %}
{% endfor %}

</div>
{% endblock %}

mysite/booker/templates/libroshechodrama.html
{% extends "home.html" %}


{% block content %}
<div class="container register">

{% load static %}

<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

<h2>Drama</h2>
{% for libros in libros_list %}
	{% for generos in libros.genero.all %}
	{% if generos.nombre == "Drama" %}
	
		<div class="col-md-4 well">
	        <div class="panel panel-primary">
	            <div class="panel-heading">
	                <h3 class="panel-title">{{ libros.nombre }}
	                {% if request.user in libros.autores.all %}
	                <a href="/borrarlibros/{{libros.id}}">&nbsp;&nbsp;
	                <span class="glyphicon glyphicon-trash"></span>
	                </a>
	                {% endif %}
	                </h3>
	            </div>
	                <div class="panel-body">
						
						<br/>
						<p style="text-align: center;">
	                    <a href="/visualizador/{{libros.id}}"><img src="{{libros.portada.url}}" height="324" width="250" ></a>
	                    </p>
	                    <br/>
	                    {{libros.sinopsis}}
	                    
	                    

	                </div>

	                <div class="panel-footer">

	                	{% load ratings %}

						{% ratings libros %}

	                	{% if libros.contenido %}
	                	<a href="{{ libros.contenido.url }}">Descarga</a>
						{% endif %}

	                </div>
	        </div>
	    </div>


	
	{% endif %}
	{% endfor %}
{% endfor %}

</div>
{% endblock %}

mysite/booker/templates/libroshechohumor.html
{% extends "home.html" %}


{% block content %}
<div class="container register">

{% load static %}

<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

<h2>Humor</h2>
{% for libros in libros_list %}
	{% for generos in libros.genero.all %}
	{% if generos.nombre == "Humor" %}
	
		<div class="col-md-4 well">
	        <div class="panel panel-primary">
	            <div class="panel-heading">
	                <h3 class="panel-title">{{ libros.nombre }}
	                {% if request.user in libros.autores.all %}
	                <a href="/borrarlibros/{{libros.id}}">&nbsp;&nbsp;
	                <span class="glyphicon glyphicon-trash"></span>
	                </a>
	                {% endif %}
	                </h3>
	            </div>
	                <div class="panel-body">
						
						<br/>
						<p style="text-align: center;">
	                    <a href="/visualizador/{{libros.id}}"><img src="{{libros.portada.url}}" height="324" width="250" ></a>
	                    </p>
	                    <br/>
	                    {{libros.sinopsis}}
	                    
	                    

	                </div>

	                <div class="panel-footer">

	                	{% load ratings %}

						{% ratings libros %}

	                	{% if libros.contenido %}
	                	<a href="{{ libros.contenido.url }}">Descarga</a>
						{% endif %}
	                </div>
	        </div>
	    </div>


	
	{% endif %}
	{% endfor %}
{% endfor %}

</div>
{% endblock %}

mysite/booker/templates/libroshechootros.html
{% extends "home.html" %}


{% block content %}
<div class="container register">

{% load static %}

<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

<h2>Otros</h2>
{% for libros in libros_list %}
	{% for generos in libros.genero.all %}
	{% if generos.nombre == "Otros" %}
	
		<div class="col-md-4 well">
	        <div class="panel panel-primary">
	            <div class="panel-heading">
	                <h3 class="panel-title">{{ libros.nombre }}
	                {% if request.user in libros.autores.all %}
	                <a href="/borrarlibros/{{libros.id}}">&nbsp;&nbsp;
	                <span class="glyphicon glyphicon-trash"></span>
	                </a>
	                {% endif %}
	                </h3>
	            </div>
	                <div class="panel-body">
						
						<br/>
						<p style="text-align: center;">
	                    <a href="/visualizador/{{libros.id}}"><img src="{{libros.portada.url}}" height="324" width="250" ></a>
	                    </p>
	                    <br/>
	                    {{libros.sinopsis}}
	                    
	                    

	                </div>

	                <div class="panel-footer">

	                	{% load ratings %}

						{% ratings libros %}

	                	{% if libros.contenido %}
	                	<a href="{{ libros.contenido.url }}">Descarga</a>
						{% endif %}

	                </div>
	        </div>
	    </div>


	
	{% endif %}
	{% endfor %}
{% endfor %}

</div>
{% endblock %}

mysite/booker/templates/libroshechopoesia.html
{% extends "home.html" %}


{% block content %}
<div class="container register">

{% load static %}

<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

<h2>Poesia</h2>
{% for libros in libros_list %}
	{% for generos in libros.genero.all %}
	{% if generos.nombre == "Poesia" %}
	
		<div class="col-md-4 well">
	        <div class="panel panel-primary">
	            <div class="panel-heading">
	                <h3 class="panel-title">{{ libros.nombre }}
	                {% if request.user in libros.autores.all %}
	                <a href="/borrarlibros/{{libros.id}}">&nbsp;&nbsp;
	                <span class="glyphicon glyphicon-trash"></span>
	                </a>
	                {% endif %}
	                </h3>
	            </div>
	                <div class="panel-body">
						
						<br/>
						<p style="text-align: center;">
	                    <a href="/visualizador/{{libros.id}}"><img src="{{libros.portada.url}}" height="324" width="250" ></a>
	                    </p>
	                    <br/>
	                    {{libros.sinopsis}}
	                    
	                    

	                </div>

	                <div class="panel-footer">

	                	{% load ratings %}

						{% ratings libros %}

	                	{% if libros.contenido %}
	                	<a href="{{ libros.contenido.url }}">Descarga</a>
						{% endif %}

	                </div>
	        </div>
	    </div>


	
	{% endif %}
	{% endfor %}
{% endfor %}

</div>
{% endblock %}

mysite/booker/templates/libroshechoromance.html
{% extends "home.html" %}


{% block content %}
<div class="container register">

{% load static %}

<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

<h2>Romance</h2>
{% for libros in libros_list %}
	{% for generos in libros.genero.all %}
	{% if generos.nombre == "Romance" %}
	
		<div class="col-md-4 well">
	        <div class="panel panel-primary">
	            <div class="panel-heading">
	                <h3 class="panel-title">{{ libros.nombre }}
	                {% if request.user in libros.autores.all %}
	                <a href="/borrarlibros/{{libros.id}}">&nbsp;&nbsp;
	                <span class="glyphicon glyphicon-trash"></span>
	                </a>
	                {% endif %}
	                </h3>
	            </div>
	                <div class="panel-body">
						
						<br/>
						<p style="text-align: center;">
	                    <a href="/visualizador/{{libros.id}}"><img src="{{libros.portada.url}}" height="324" width="250" ></a>
	                    </p>
	                    <br/>
	                    {{libros.sinopsis}}
	                    
	                    

	                </div>

	                <div class="panel-footer">

	                	{% load ratings %}

						{% ratings libros %}

	                	{% if libros.contenido %}
	                	<a href="{{ libros.contenido.url }}">Descarga</a>
						{% endif %}

	                </div>
	        </div>
	    </div>


	
	{% endif %}
	{% endfor %}
{% endfor %}

</div>
{% endblock %}